//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTunesAgent.UI.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iTunesAgent.UI.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		internal static System.Drawing.Bitmap add {
			get {
				object obj = ResourceManager.GetObject("add", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap add_small {
			get {
				object obj = ResourceManager.GetObject("add_small", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap associations {
			get {
				object obj = ResourceManager.GetObject("associations", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
		///&lt;configuration xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
		///  &lt;usebaloon&gt;true&lt;/usebaloon&gt;
		///  &lt;closewithitunes&gt;true&lt;/closewithitunes&gt;
		///  &lt;itafolder&gt;true&lt;/itafolder&gt;
		///  &lt;warnonsystemdrive&gt;true&lt;/warnonsystemdrive&gt;
		///  &lt;checkforupdates&gt;true&lt;/checkforupdates&gt;
		///&lt;/configuration&gt;.
		/// </summary>
		internal static string DEFAULT_CONFIGURATION {
			get {
				return ResourceManager.GetString("DEFAULT_CONFIGURATION", resourceCulture);
			}
		}
		
		internal static System.Drawing.Bitmap devices_icon {
			get {
				object obj = ResourceManager.GetObject("devices_icon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap download {
			get {
				object obj = ResourceManager.GetObject("download", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap globe {
			get {
				object obj = ResourceManager.GetObject("globe", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap help {
			get {
				object obj = ResourceManager.GetObject("help", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap home {
			get {
				object obj = ResourceManager.GetObject("home", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Icon ita_new {
			get {
				object obj = ResourceManager.GetObject("ita_new", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to English.
		/// </summary>
		internal static string LangEnglish {
			get {
				return ResourceManager.GetString("LangEnglish", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to German (Deutsch).
		/// </summary>
		internal static string LangGerman {
			get {
				return ResourceManager.GetString("LangGerman", resourceCulture);
			}
		}
		
		internal static System.Drawing.Bitmap media_players {
			get {
				object obj = ResourceManager.GetObject("media_players", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap playlist {
			get {
				object obj = ResourceManager.GetObject("playlist", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap preferences {
			get {
				object obj = ResourceManager.GetObject("preferences", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		internal static System.Drawing.Bitmap remove {
			get {
				object obj = ResourceManager.GetObject("remove", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Unable to write default configuration. Please ensure the application is run as a user with necessary access to your user directory..
		/// </summary>
		internal static string StrDefaultConfigWriteError {
			get {
				return ResourceManager.GetString("StrDefaultConfigWriteError", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Never.
		/// </summary>
		internal static string StrDeviceLastSyncNever {
			get {
				return ResourceManager.GetString("StrDeviceLastSyncNever", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Offline.
		/// </summary>
		internal static string StrDeviceStatusOffline {
			get {
				return ResourceManager.GetString("StrDeviceStatusOffline", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Connected.
		/// </summary>
		internal static string StrDeviceStatusOnline {
			get {
				return ResourceManager.GetString("StrDeviceStatusOnline", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to You are running the newest version,.
		/// </summary>
		internal static string StrHomePanelYouAreRunningVersion {
			get {
				return ResourceManager.GetString("StrHomePanelYouAreRunningVersion", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to The following software have been located:.
		/// </summary>
		internal static string StrMediaSoftwareStatusPrefix {
			get {
				return ResourceManager.GetString("StrMediaSoftwareStatusPrefix", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to I am currenty not managing any devices for you..
		/// </summary>
		internal static string StrNoDevicesManaged {
			get {
				return ResourceManager.GetString("StrNoDevicesManaged", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to I have not been able to detect any installation of iTunes on your computer. Please make sure iTunes is installed, then restart me..
		/// </summary>
		internal static string StrNoITunesDetected {
			get {
				return ResourceManager.GetString("StrNoITunesDetected", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Your music will be copied to.
		/// </summary>
		internal static string StrPlaylistAssociationCurrentlySelected {
			get {
				return ResourceManager.GetString("StrPlaylistAssociationCurrentlySelected", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Restart the application so the new settings can take effect.
		/// </summary>
		internal static string StrRestartApplicationSoSettingsTakeEffect {
			get {
				return ResourceManager.GetString("StrRestartApplicationSoSettingsTakeEffect", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Configure your device.
		/// </summary>
		internal static string StrWizardConfigureYourDevice {
			get {
				return ResourceManager.GetString("StrWizardConfigureYourDevice", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Name your device.
		/// </summary>
		internal static string StrWizardNamePageTitle {
			get {
				return ResourceManager.GetString("StrWizardNamePageTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Associate playlists with device.
		/// </summary>
		internal static string StrWizardPlaylistsPageTitle {
			get {
				return ResourceManager.GetString("StrWizardPlaylistsPageTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Summary.
		/// </summary>
		internal static string StrWizardSummaryPageTitle {
			get {
				return ResourceManager.GetString("StrWizardSummaryPageTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Choose your device type.
		/// </summary>
		internal static string StrWizardTypeSelectionPageTitle {
			get {
				return ResourceManager.GetString("StrWizardTypeSelectionPageTitle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Add a new device.
		/// </summary>
		internal static string StrWizardWelcomeAddNewPage {
			get {
				return ResourceManager.GetString("StrWizardWelcomeAddNewPage", resourceCulture);
			}
		}
	}
}
